// <auto-generated />
using Api_ITI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_ITI.Migrations
{
    [DbContext(typeof(apiDbContext))]
    [Migration("20260517063152_InitWithProject")]
    partial class InitWithProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_ITI.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            FullName = "Mohamed Taha",
                            PhoneNumber = "01012345678",
                            Position = "Developer",
                            ProjectId = 1,
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 2,
                            Department = "IT",
                            FullName = "Nour Khaled",
                            PhoneNumber = "01098765432",
                            Position = "Tester",
                            ProjectId = 1,
                            Salary = 7000m
                        },
                        new
                        {
                            Id = 3,
                            Department = "IT",
                            FullName = "Hana Sami",
                            PhoneNumber = "01123456789",
                            Position = "Designer",
                            ProjectId = 2,
                            Salary = 9000m
                        },
                        new
                        {
                            Id = 4,
                            Department = "HR",
                            FullName = "Tarek Adel",
                            PhoneNumber = "01234567890",
                            Position = "Manager",
                            ProjectId = 3,
                            Salary = 11000m
                        });
                });

            modelBuilder.Entity("Api_ITI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Redesign company website",
                            Name = "Website Redesign"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Build Android & iOS app",
                            Name = "Mobile App"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Internal management system",
                            Name = "ERP System"
                        });
                });

            modelBuilder.Entity("Api_ITI.Models.Employee", b =>
                {
                    b.HasOne("Api_ITI.Models.Project", "Project")
                        .WithMany("Employees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Api_ITI.Models.Project", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
